<?php

namespace Portafolio\PageBundle\Repository;

/**
 * agenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agenciaRepository extends BaseRepository
{
    public function getAgencia($nombre, $obj = false)
    {
        if (!$obj) {
            return $this->createQueryBuilder('a')
                ->where('a.nombre = :nombre
            ')
                ->setParameters(array('nombre' => $nombre))
                ->getQuery()
                ->getArrayResult();
        }
        else {
            return $this->createQueryBuilder('a')
                ->where('a.nombre = :nombre
            ')
                ->setParameters(array('nombre' => $nombre))
                ->getQuery()
                ->getResult();
        }
    }
}
