<?php

namespace Portafolio\PageBundle\Repository;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRepository extends BaseRepository
{

}
