<?php

namespace Portafolio\PageBundle\Repository;
use Portafolio\PageBundle\Entity\agencia;

/**
 * viajesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class viajesRepository extends BaseRepository
{
    public function getViajes($codigo, $obj = false)
    {
        if (!$obj) {
            return $this->createQueryBuilder('v')
                ->where('v.codigo = :codigo
            ')
                ->setParameters(array('codigo' => $codigo))
                ->getQuery()
                ->getArrayResult();
        }
        return $this->createQueryBuilder('v')
            ->where('v.codigo = :codigo')
            ->setParameters(array('codigo' => $codigo))
            ->getQuery()
            ->getResult();
    }

    public function getAgencia($nombre_agencia, $obj = false)
    {
        if (!$obj) {
            return $this->createQueryBuilder('v')
                ->where('v.nombre = :nombre
            ')
                ->setParameters(array('nombre' => $nombre_agencia))
                ->getQuery()
                ->getArrayResult();
        }
        return $this->createQueryBuilder('v')
            ->where('v.nombre = :nombre')
            ->setParameters(array('nombre' => $nombre_agencia))
            ->getQuery()
            ->getResult();
    }

    public function updateDataViaje($data)
    {
        $em = $this->getEntityManager();

        if ( isset($data['cedula_viajero']) ) {
            $stmt = $em->getConnection()->prepare("select * from viajero where cedula = '" . $data['cedula_viajero'] . "'");
            $stmt->execute();
            $viajero = $stmt->fetchAll();
            $existViajero = ($stmt->rowCount() >= 1);
        }
        if ( isset($data['agencia_nombre']) ) {
            $stmt = $em->getConnection()->prepare("select * from agencia where nombre = '" . $data['agencia_nombre'] . "'");
            $stmt->execute();
            $agency = $stmt->fetchAll();
            $existAgencia = ($stmt->rowCount() >= 1);
        }
        if ( isset($data['codigo_search']) AND $existAgencia AND $existViajero) {
            $sql = "update viajes set ";
            $where = " where id = (select id from viajes where codigo = '" . $data['codigo_search'] . "')";
            if (isset($data['fecha'])) {
                $fecha = new \DateTime($data['fecha']);
                $updateFecha =  "fecha = '" . $fecha->format('d-m-Y') . "' ";
            }
            else
                $updateFecha = null;
            $updateDestino = isset($data['destino']) ? "destino = '" . $data['destino'] . "' " : null;
            $updateCodigo = isset($data['codigo']) ? "codigo = '" . $data['codigo'] . "' " : null;
            $updateOrigen = isset($data['origen']) ? "origen = '" . $data['origen'] . "' " : null;
            $updateNombre = isset($data['nombre']) ? "nombre = '" . $data['nombre'] . "' " : null;
            $updateOtros = isset($data['otros']) ? "otros = '" . $data['otros'] . "' " : null;
            $updateViajero = "viajero_id = '" . $viajero[0]['id'] . "' ";
            $updateAgencia = "agencia_id = '" . $agency[0]['id'] . "' ";

            $set = [];
            array_push($set, $updateFecha);
            array_push($set, $updateDestino);
            array_push($set, $updateOrigen);
            array_push($set, $updateCodigo);
            array_push($set, $updateNombre);
            array_push($set, $updateOtros);
            array_push($set, $updateViajero);
            array_push($set, $updateAgencia);

            foreach ($set as $cadena) {
                if (!is_null($cadena))
                    $sql = $sql . $cadena . ",";
            }
            $sql = rtrim($sql, ',');
            $sql = $sql . $where;

            $stmt = $em->getConnection()->prepare($sql);
            $stmt->execute();
            return $stmt->rowCount();
        }
    }
}
