fos_user_security_login:
    path: /login
    defaults: { _controller: PortafolioPageBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: PortafolioPageBundle:Security:check }

fos_user_security_logout:
    path: /logout
    defaults: { _controller: PortafolioPageBundle:Security:logout }
