portafolio_page_homepage:
    path:     /
    defaults: { _controller: PortafolioPageBundle:Default:index }

get_user:
    path: /getUser
    defaults: { _controller: PortafolioPageBundle:Default:getUser}
    options:
        expose: true

create_user:
    path: /createUser
    defaults: { _controller: PortafolioPageBundle:Default:createUsers}
    options:
        expose: true

created_view_user:
    path: /createdViewUser
    defaults: { _controller: PortafolioPageBundle:Default:newUserCreatedView}
    options:
        expose: true