parameters:
    repository.factory: Portafolio\PageBundle\Resources\Factory\RepositoryFactory
    command.handler.conection: Portafolio\PageBundle\Service\CommandHandlerConnected
    core.validator: Portafolio\PageBundle\Service\CoreValidator

services:
#    portafolio_page.example:
#        class: Portafolio\PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    repositories:
        class: %repository.factory%
        arguments: ["@doctrine"]
    bus.request:
        class: %command.handler.conection%
        arguments: ["@service_container", "@repositories"]
    core_validator:
        class: %core.validator%
        arguments: ["@service_container"]
