services:
#    portafolio_page.example:
#        class: Portafolio\PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    list_repositories:
        class: Portafolio\PageBundle\Resources\Factory\RepositoryFactory
        arguments: ["@doctrine"]
    command_handler_connected:
        class: Portafolio\PageBundle\Service\CommandHandlerConnected
        arguments: ["@service_container", "@list_repositories"]
