parameters:
    service.factory: Portafolio\PageBundle\Resources\Factory\ServiceFactory
    command.handler.conection: Portafolio\PageBundle\Service\CommandHandlerConnected

services:
#    portafolio_page.example:
#        class: Portafolio\PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    services:
        class: %service.factory%
        arguments: ["@service_container"]
    bus.request:
        class: %command.handler.conection%
        arguments: ["@service_container", "@services"]
